### ISSUE TITLE
Example docker-compose.yml for deployment

### ISSUE THREAD

**Issue by pwaldon** [giorgimode/SpotMyStatus#53]
Hi,

I'm trying to deploy it locally for debugging purposes, but having hard time configuring it will all the env variables and slack configuration. Can you please post some more informations regarding deployment?

Currently I'm having something like below:
```  
  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  backend:
    image: eclipse-temurin:11
    ports:
      - 8090:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SLACK_CLIENT_ID=<ID>
      - SLACK_CLIENT_SECRET=<SECRET>
      - SIGNING_SECRET=<SIGN_SECRET>
      - SMTP_HOST=smtp.gmail.com
      - SMTP_MAIL_SENDER=email@gmail.com
      - SMTP_MAIL_RECIPIENT=email@gmail.com
      - ADMIN_USERS=test1-user-name
    volumes:
      - ./SpotMyStatus:/code
    working_dir: /code
    entrypoint: bash
    command: -c "java -jar /code/backend/build/libs/spotmystatus-2.0.1.jar"
    ```

Thanks
